// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlmokucczozigaaelhrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbW9rdWNjem96aWdhYWVsaHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzA0NjEsImV4cCI6MjA2NTUwNjQ2MX0.ApqSD3Wp5EGdHPlsC4eoVOixQYEK9eUO84ukC609QuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);